In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.Tensor(5,3)
x = torch.rand(5,3)

In [4]:
x

tensor([[0.4392, 0.5887, 0.5887],
        [0.3625, 0.3976, 0.2391],
        [0.1869, 0.2187, 0.7701],
        [0.5841, 0.5910, 0.6626],
        [0.8980, 0.0096, 0.4079]])

In [5]:
x.size()

torch.Size([5, 3])

In [9]:
y = torch.rand(5,3)

In [8]:
x+y

tensor([[1.4100, 0.9655, 1.0201],
        [0.7220, 0.6935, 1.1196],
        [0.8161, 0.2690, 1.6136],
        [1.3751, 0.7224, 0.9884],
        [1.7628, 0.9849, 1.2975]])

In [10]:
torch.add(x,y)

tensor([[1.1142, 1.3795, 1.0238],
        [0.7915, 0.4429, 1.0217],
        [0.5730, 0.8696, 1.3534],
        [1.4925, 1.3232, 1.3062],
        [1.8547, 0.0908, 0.9004]])

In [12]:
result = torch.Tensor(5,3)

In [13]:
torch.add(x,y,out=result)

tensor([[1.1142, 1.3795, 1.0238],
        [0.7915, 0.4429, 1.0217],
        [0.5730, 0.8696, 1.3534],
        [1.4925, 1.3232, 1.3062],
        [1.8547, 0.0908, 0.9004]])

In [14]:
y.add_(x)

tensor([[1.1142, 1.3795, 1.0238],
        [0.7915, 0.4429, 1.0217],
        [0.5730, 0.8696, 1.3534],
        [1.4925, 1.3232, 1.3062],
        [1.8547, 0.0908, 0.9004]])

In [15]:
a = torch.ones(5)

In [16]:
b = a.numpy()

In [17]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [18]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [19]:
print(b)

[2. 2. 2. 2. 2.]


In [20]:
from torch.autograd import Variable

In [21]:
x = Variable(torch.ones(2,2), requires_grad = True)

In [22]:
y = x +2

In [23]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [25]:
y.grad_fn

In [26]:
z = y*y*3

In [27]:
out = z.mean()

In [28]:
out.backward()

In [29]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [30]:
x = torch.randn(3)

In [32]:
x = Variable(x, requires_grad = True)

In [33]:
y = x * 2

In [34]:
while y.data.norm()<1000:
    y = y * 2

In [35]:
gradients = torch.FloatTensor([0.1,1.0,0.0001])

In [36]:
y.backward(gradients)

In [37]:
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

# 定义一个神经网络

In [39]:
import torch.nn as nn
import torch.nn.functional as F

In [42]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(1,6,5)
    self.conv2 = nn.Conv2d(6,16,5)
    self.fc1 = nn.Linear(16*5*5,120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84,10)
    
  def forward(self,x):
    x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    x = F.max_pool2d(F.relu(self.conv2(x)),2)
    x = x.view(-1,self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self,x):
    size = x.size()[1:]
    num_features = 1
    for s in size:
        num_features *= s
    return num_features

In [43]:
net = Net()

In [44]:
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [45]:
params = list(net.parameters())

In [46]:
print(len(params))

10


In [47]:
print(params[0].size())

torch.Size([6, 1, 5, 5])


In [48]:
input = Variable(torch.randn(1,1,32,32))

In [49]:
out = net(input)

In [50]:
net.zero_grad()

In [51]:
out.backward(torch.randn(1,10))